# This is a basic workflow to help you get started with Actions

name: CICD setup for deploying mule application using Github actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # One liner script
      - name: Test script
        run: echo Test script executed
        
      # Building Mule application
      - name: Building mule app
        run: mvn clean -B install -DskipTests -s settings.xml
        
      # Running test cases
      - name: Running Munit test cases
        run: mvn test -s settings.xml
        
      # Pushing artifacts to Anypoint exchange
      - name: Pushing artifacts
        run: mvn deploy -s settings.xml
        
      # Deploying Mule application to CH2.0
      - name: Deploying mule app
        run: mvn deploy -DmuleDeploy -s settings.xml
